version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backendnew
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - STORAGE_DATA_DIR=/app/data
      - SCANNER_SCRIPTS_DIR=/app/scripts
    volumes:
      - backend_data:/app/data
      - ./backendnew/scripts:/app/scripts:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - regtech-network

  # Frontend service
  frontend:
    build:
      context: ./frontendv2
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - regtech-network

networks:
  regtech-network:
    driver: bridge

volumes:
  backend_data:
    driver: local
